from pathlib import Path
from lxml import etree as E
import json,re,collections
ROOT=Path(__file__).resolve().parents[4]
OUT=Path(__file__).parent
I=json.loads((ROOT/'audit/logical-order-round2/id-index.json').read_text(encoding='utf-8-sig'))
T=json.loads((ROOT/'audit/logical-order-round2/task-inventory.json').read_text(encoding='utf-8-sig'))
SHA='9a9d110af839b539fe598de66ecc4320a4126af4'
XI='{http://www.w3.org/2001/XInclude}include'; ID='{http://www.w3.org/XML/1998/namespace}id'
W={}; used={}
RANGES={'c16s1-subsec-0-forms-functions':[108,137],'c19s2-incompressible-flow-and-divergence-free-fields':[512,525],
'c20s1-proj-quadric-surfaces':[20,79],'c20s1-proj-tangent-planes':[201,333],'c20s1-proj-gradient-fields':[475,573],'c20s1-proj-parameter-grids':[692,803],
'c20s2-proj-constrained-design':[22,120],'c20s2-proj-least-squares':[176,300],'c20s2-proj-entropy':[388,447],'c20s2-proj-gradient-descent':[576,692],
'c20s3-proj-mass-from-density':[29,182],'c20s3-proj-moments-of-inertia':[278,474],'c20s3-proj-change-of-variables':[576,803],'c20s3-proj-monte-carlo':[917,1110],
'c20s4-project-work-around-closed-curves':[19,159],'c20s4-project-flux-through-complicated-surfaces':[256,390],'c20s4-project-greens-theorem-area-from-gps':[483,623],'c20s4-project-divergence-theorem-flux-balance':[711,850],
'c20s5-project-1-translate-classical-into-forms':[29,186],'c20s5-project-2-closed-not-exact':[232,368],'c20s5-project-3-generalized-stokes-cube':[416,515],'c20s5-project-4-orientation-errors':[567,681]}
def ev(i,lines=None):
 x=I[i];return {'snapshot':SHA,'path':x['path'],'xml_id':i,'lines':lines or RANGES.get(i) or x['lines']}
def cite(i):
 x=ev(i);used[i]=x;return f"`{i}` ({x['path']}:{x['lines'][0]}–{x['lines'][1]})"
def w(i,answer,supports,status='supported'):
 for s in supports:assert s in I,s
 W[i]={'solution_outline':answer,'support_ids':supports,'verdict':status}
def group(i,answer,supports,status='supported'):w(i,answer,supports,status)

# Every formal checkpoint is answered independently; these are not topic matches.
CK={
'checkpoint-16-1-why-orient-points':('Opposite endpoint signs produce f(b)-f(a); all-positive points would produce a sum and would not telescope.',['c16s1-def-0-form']),
'checkpoint-16-1-why-wedge-sign':('Swapping the ordered tangent edges reverses signed area, while ordinary area forgets that order.',['c2s7-def-wedge-product-dx-dy','c16s1-def-2-form']),
'checkpoint-16-1-why-stop-at-three':('Four tangent inputs in R3 are linearly dependent; an alternating four-direction measurement is zero. The coordinate construction has only three distinct directions.',['c2s7-def-volume-form-dx-dy-dz']),
'checkpoint-16-2-vector-vs-covector':('A vector is a displacement input; a covector is a linear scalar-valued measurement of that input. Coordinates alone do not identify their roles.',['c16s2-def-covector']),
'checkpoint-16-2-covector-field-meaning':('The base point selects the local measuring coefficients: e.g. wind/work depends on where the same velocity occurs.',['c16s2-def-evaluating-a-1-form']),
'checkpoint-16-2-why-gradient-needs-dot-product':('The inner product represents the linear functional by a vector; df exists without that metric choice. Different metrics change its representing gradient.',['c16s2-thm-differential-represented-by-gradient']),
'checkpoint-16-3-sign-means-orientation':('An ordered pair of edges determines orientation. Reversing that order negates the determinant and signed area.',['c16s3-def-wedge-product-two-covectors']),
'checkpoint-16-3-why-self-wedge-vanishes':('Two identical scalar measurements cannot distinguish two independent directed area coordinates: alpha(u)alpha(v)-alpha(v)alpha(u)=0.',['c16s3-def-wedge-product-two-covectors']),
'checkpoint-16-3-why-three-shadows-in-space':('There are three distinct coordinate two-direction choices xy,yz,zx in R3, but just xy in R2; each gives a signed projected area.',['c16s3-ex-tilted-surface-patch']),
'checkpoint-16-4-why-degrees-do-not-mix':('Homogeneous k-forms take k tangent inputs. A one-input and two-input measurement are not a single homogeneous form; the text is not claiming mixed-degree sums are impossible in a larger algebra.',['c16s1-def-1-form','c16s1-def-2-form']),
'checkpoint-16-4-no-room-above-n':('Expand a coordinate (n+1)-fold wedge: one coordinate factor repeats, hence alternation makes each term zero. The checkpoint itself supplies this hint.',['c16s4-def-multiply-form-by-function','checkpoint-16-4-no-room-above-n']),
'checkpoint-16-4-sign-as-orientation':('Moving k ordered directions past l others entails kl adjacent swaps, each reversing orientation; total sign is (-1)^(kl).',['c16s4-thm-sign-rule-swapping']),
'checkpoint-16-5-why-pullback-back':('First push tangent vectors by DT, then apply the target measurement. This defines a source covector, so forms travel from target to source.',['c16s5-def-pullback-coordinate']),
'checkpoint-16-5-wedge-becomes-cross':('The three coordinate two-by-two minors are exactly the components of r_u cross r_v: both encode signed projected areas.',['c16s5-def-pullback-coordinate','c16s3-ex-tilted-surface-patch']),
'checkpoint-16-5-jacobian-sign':('A negative determinant means the parameter coordinate frame induces the opposite target orientation. Absolute area removes that sign; an oriented form retains it.',['c16s5-def-pullback-coordinate','c12s5-subsec-orientation-versus-absolute-value']),
'checkpoint-16-6-degree-matches-curve':('Pulling back a 1-form produces one coefficient times dt, measuring one tangent velocity. A two-form pulls back to zero on a one-dimensional parameter interval.',['c16s5-ex-pullback-area-form','c16s6-def-integral-1-form-curve']),
'checkpoint-16-6-why-independence-holds':('A compatible once-covering reparametrization changes the coefficient and the parameter increment by inverse compensating substitution factors. Curve substitution and surface change of variables provide the actual operation.',['c16s6-def-integral-1-form-curve','c16s6-def-integral-2-form-surface','c12s3-thm-change-of-variables-plane']),
'checkpoint-16-6-orientation-gives-sign':('Changing a compatible oriented frame to the opposite one changes the evaluation of an alternating form by -1; ordinary unsigned area is a different integral.',['c16s6-thm-reparametrize-curve','c16s6-thm-reparametrize-surface']),
'checkpoint-17-1-measures-not-stores':('dT_P is the whole linear map (a,b) maps to 3a-b/3; 7 is only its evaluation at (2,-3).',['c16s2-def-covector']),
'checkpoint-17-1-why-dot-product':('df is already a scalar-valued linear measurement; the dot product identifies its representing gradient vector.',['c17s1-thm-gradient-represents-df']),
'checkpoint-17-1-speed-scales-rate':('Linearity gives df(2v)=2df(v): same heading at twice the speed changes the reading twice as fast.',['c17s1-def-exterior-derivative-0-form']),
'checkpoint-17-2-why-2-form':('The first circulation imbalance around a tiny rectangle is a signed area measurement (Q_x-P_y) dx wedge dy.',['c14s4-thm-greens-for-1-forms']),
'checkpoint-17-2-curl-not-new':('The same exterior derivative has three signed-area coefficients in R3; the flux dictionary packages those coefficients as the curl vector.',['c17s2-thm-exterior-derivative-work-form-is-curl']),
'checkpoint-17-2-boundary-meets-inside':('Add local circulation balances; each internal edge occurs in both directions, leaving the outer boundary.',['c14s4-thm-greens-for-1-forms']),
'checkpoint-17-3-one-operation-three-names':('The degree determines which classical dictionary applies: d on functions is df, on work forms is curl flux, and on flux forms is divergence volume.',['c17s1-def-exterior-derivative-0-form','c17s2-thm-exterior-derivative-work-form-is-curl','c17s3-thm-d-flux-is-divergence-volume-form']),
'checkpoint-17-3-boundary-flux-versus-interior-source':('Net outward crossing is total source density inside; internal crossings cancel in pairs.',['c17s3-thm-d-flux-is-divergence-volume-form']),
'checkpoint-17-3-zero-divergence-but-nonzero-flux':('The form is undefined at the enclosed origin. Stokes/divergence cannot use that ball; a shell has outer 4pi and inner -4pi.',['c17s3-thm-divergence-theorem-form-version','c17s3-ex-hidden-singularity-source']),
'checkpoint-17-4-wedge-does-the-work':('Equal mixed coefficients cancel because dy wedge dx=-dx wedge dy and repeated directions vanish. A symmetric product would add them.',['c9s3-thm-equality-of-mixed-partials','c16s3-def-wedge-product-two-covectors']),
'checkpoint-17-4-gradient-no-swirl':('A global potential changes by endpoint difference, which is zero on a closed path; its C2 local curl is zero too.',['c17s4-thm-d-df-zero']),
'checkpoint-17-4-two-rules-one-truth':('For sufficiently regular forms, Stokes applied twice relates integral of d² eta to the empty twice-boundary, both zero. This is a consistency interpretation, not an independent proof of arbitrary patching.',['c17s4-thm-d-domega-zero','c15s5-thm-stokes']),
'checkpoint-17-5-why-exact-is-closed':('A global primitive gives cancellation of mixed partials everywhere and zero relevant boundary integrals. Closedness only tests local coefficients and need not provide that primitive.',['c17s5-def-exact-form','c17s5-def-closed-form','c17s4-thm-d-domega-zero']),
'checkpoint-17-5-what-the-hole-breaks':('The origin prevents a global single-valued angle. The unit-circle integral is 2pi, which rules out a global potential although the local coefficient derivative is zero.',['c17s2-ex-hidden-singularity-breaks-theorem','c17s5-def-exact-form']),
'checkpoint-17-5-local-versus-global':('Local zero circulation cannot detect a noncontractible loop; the angle example gives the obstruction. The statement of the simply connected theorem supplies the positive implication, with GF-01 proof limitation.',['c17s5-thm-simply-connected-potential']),
'checkpoint-17-6-loop-and-hole':('The circle cannot be filled/contracted through the omitted origin within this domain; locally zero curl coexists with its 2pi line integral.',['c17s5-def-closed-form','c17s2-ex-hidden-singularity-breaks-theorem']),
'checkpoint-17-6-where-flux-lives':('The zero-source assertion is only away from the origin. On an admissible shell outer and inner flux cancel; the full ball is outside the theorem hypotheses.',['c17s3-ex-hidden-singularity-source']),
'checkpoint-17-6-two-closeds':('Closed form means derivative zero; closed geometric object means no boundary. Zero integral requires a filling in the domain (or exactness), not just these two unrelated adjectives.',['c17s5-def-closed-form','c17s5-def-exact-form']),
'checkpoint-19-1-why-the-minus-sign':('In the source-free balance immediately above, positive outward flux decreases storage. Later sources could offset it; the checkpoint uses the present source-free equation.',['c19s1-subsec-fixed-window-moving-dye']),
'checkpoint-19-1-flow-along-the-wall':('Tangential J is perpendicular to n, so J dot n=0 regardless of its speed.',['c19s1-def-flux-density']),
'checkpoint-19-1-window-versus-blob':('E is a fixed spatial window; particles cross its boundary. A moving material blob is a different balance setup.',['c19s1-subsec-fixed-region-assumption']),
'checkpoint-19-2-every-region':('A single integral may have positive/negative cancellation. If a continuous nonzero integrand had positive value at a point, a small neighborhood would have strictly positive integral, contradicting every-region balance.',['c19s2-deriving-the-local-balance-law']),
'checkpoint-19-2-two-observers':('D rho/Dt=rho_t+v dot grad rho is the moving particle rate; rho div v describes expansion/compression. Translation can give D rho/Dt=0 while a fixed sensor has rho_t nonzero.',['c19s2-expansion-compression-and-the-material-derivative']),
'checkpoint-19-2-divergence-free-still-moves':('It preserves local material volume, not location, shape, or orientation; rotations/shears exhibit this directly.',['c19s2-incompressible-flow-and-divergence-free-fields','c19s2-ex-rotating-incompressible-flow','c19s2-ex-shear-flow-zero-divergence']),
'checkpoint-19-3-laplacian-meaning':('The four-neighbor Taylor average minus the center is h² Delta u/4+o(h²). Positive Delta u means the center is colder than that average to leading order and u_t>0.',['c19s3-ex-warm-bump-on-a-rod','c19s3-def-heat-equation']),
'checkpoint-19-3-heat-versus-wave-time':('Heat sets a first time rate by imbalance; wave motion sets acceleration and retains momentum. The local decaying and traveling examples illustrate these models without requiring an ODE existence theorem.',['c19s3-def-heat-equation','c19s3-def-wave-equation','c19s3-ex-a-traveling-wave']),
'checkpoint-19-3-why-shared-operator':('Each model responds to the sum of spatial second-order imbalances; different time/storage laws combine with the same local curvature operator.',['c19s3-ex-warm-bump-on-a-rod','c19s3-subsec-vibrating-membranes','c19s3-def-laplaces-equation']),
'checkpoint-19-4-surface-independence':('Ampere-Maxwell identifies J+D_t=dH. Its integral over an admissible spanning surface equals the same boundary integral of H. The added displacement term provides this balance; no general exactness-from-closedness theorem is needed.',['c19s4-subsec-ampere-maxwell-law','c19s4-subsec-one-loop-two-surfaces','c18s2-thm-generalized-stokes']),
'checkpoint-19-4-conservation-built-in':('Apply d to dH=J+D_t: 0=dJ+(dD)_t=dJ+Q_t, using C2 commutation and Gauss dD=Q.',['c19s4-subsec-charge-conservation-d-squared','c17s4-thm-d-domega-zero']),
'checkpoint-19-4-gateway-elegance':('E and B appear as coefficient pieces of one spacetime 2-form F; d4F=0 simultaneously encodes both homogeneous equations. This answer requires no Lorentz-transform computation or Hodge star; the hint is motivational.',['c19s4-subsec-what-changes-in-space-time']),
'checkpoint-19-5-saddle-balance':('For x²-y² the second derivatives are 2 and -2. Their sum, not either individual bending, vanishes.',['c19s5-def-harmonic-function','c19s5-ex-saddle-in-balance']),
'checkpoint-19-5-maximum-principle':('If every surrounding value is at most the maximum, continuity and equality to the circle average force equality all around. All sufficiently small radii give a constant disk. The global extension invokes the supplied statement with GF-03 proof limitation.',['c19s5-thm-mean-value-property','c19s5-thm-no-interior-maximum']),
'checkpoint-19-5-energy-boundary':('Without prescribed edge values, the constant zero function has energy zero and could replace any nonconstant field. Fixed boundary data makes the comparison meaningful.',['c19s5-def-dirichlet-energy','c19s5-thm-harmonic-minimize-dirichlet']),
}

# Chapter 18 conceptual checkpoints, in actual source order.
ANS18={
'hole-clockwise':'Keep the region on the left; walking the inner hole clockwise does that.',
'which-side-forces-the-walk':'Changing only the boundary traversal negates one side of Stokes. The selected normal induces the compatible traversal.',
'boundary-of-a-boundary':'Each box edge occurs twice with opposite induced directions, so the oriented chain cancels.',
'why-omega-one-degree-less':'The boundary is k-1 dimensional, so it accepts a (k-1)-form.',
'why-d-raises-degree':'d converts the boundary measurement into its interior k-dimensional density.',
'why-interior-cancels':'Adjacent regions traverse a shared edge oppositely and contribute equal negative integrals.',
'why-minus-sign':'The positively traversed interval enters at a and exits at b, hence signed boundary b-a.',
'interior-cancellation':'Interior partition points are an exit of one interval and entry of the next; their function values cancel.',
'boundary-theorem-view':'The total derivative integral is endpoint data f(b)-f(a), an oriented boundary measurement.',
'curl-meaning':'Q_x-P_y is infinitesimal counterclockwise circulation per unit signed area.',
'inner-orientation':'Changing the inner direction adds its area instead of subtracting the hole, breaking Stokes.',
'one-theorem':'Use either the work form P dx+Q dy or the flux form P dy-Q dx; d computes curl or divergence accordingly.',
'why-curl-appears':'Expanding d(P dx+Q dy+R dz) with antisymmetry produces exactly the three curl coefficients.',
'only-the-boundary':'For this exact 2-form d omega, all admissible surfaces induce the same boundary integral; arbitrary 2-forms need not.',
'missing-point-circulation':'The chosen spanning disk includes a point where the form is undefined, so its hypotheses fail.',
'form-degree-jump':'Boundary flux is measured on a surface; total source density is measured in the enclosed volume.',
'net-flux-meaning':'Only net crossing remains after internal transfers cancel; the boundary integral equals total divergence.',
'curl-flux-vanishes':'d(d omega)=0 for C2 coefficients, so Stokes on the solid gives zero closed-surface flux.',
'why-interior-edges-cancel':'Each shared edge carries opposite induced orientations, so its two integrals cancel.',
'why-pieces-assemble':'Add exact rectangle identities and cancel shared edges; general curved-domain limiting is separately an outline.',
'twin-facts':'Apply Stokes twice at the appropriate degrees: the twice boundary cancels, and the integral of d² is zero.',
'why-signs-on-points':'Outward/end signs are b-a and recover the endpoint difference, not a sum.',
'why-degree-two':'The boundary of a solid is two-dimensional and measures two tangent directions.',
'one-theorem-four-faces':'Dimensions 1,2,2-in-space,3 and the work/flux dictionaries yield FTC, Green, classical Stokes, divergence.',
'orientation-truth-value':'Only the clockwise line integral was negated; the fixed positively oriented square integral remained 1.',
'why-zero-fails':'The field is defined only on a punctured domain; the disk needed by the careless step is inadmissible.',
'jump-hidden-edge':'H has a jump at y=0, so d omega is not defined there in the C1 calculus; the missing internal interface contribution is -2.',
}
S18={1:['c18s1-def-oriented-boundary-of-an-interval','c18s1-def-positive-boundary-orientation-plane','c18s1-def-boundary-orientation-of-a-surface','c18s1-ex-boundary-orientation-of-a-box'],2:['c18s2-thm-generalized-stokes'],3:['c18s3-thm-ftc-as-stokes'],4:['c18s4-thm-green-as-stokes','c18s1-def-positive-boundary-orientation-plane'],5:['c17s2-thm-exterior-derivative-work-form-is-curl','c18s5-thm-classical-stokes-as-generalized'],6:['c17s3-thm-d-flux-is-divergence-volume-form','c18s6-thm-divergence-theorem-as-generalized-stokes','c17s4-thm-d-domega-zero'],7:['c18s3-thm-ftc-as-stokes','c10s3-thm-fubini-rectangles','c18s2-thm-generalized-stokes'],8:['c18s2-thm-generalized-stokes','c18s1-def-outward-first-convention'],9:['c18s4-thm-green-as-stokes','c14s6-a-jump-inside-is-a-hidden-edge','c17s2-ex-hidden-singularity-breaks-theorem']}
for t in T:
 k=t['task_key']
 if k.startswith('checkpoint-18-'):
  n=int(k.split('-')[2]);suffix='-'.join(k.split('-')[3:]);CK[k]=(ANS18[suffix],S18[n])
for k,(a,s) in CK.items():w(k,a,s)

# Availability audit: use the actual earlier explanation rather than a nearby later box.
for k,ss in {
'checkpoint-16-1-why-orient-points':['c16s1-subsec-0-forms-functions'],
'checkpoint-16-1-why-wedge-sign':['c2s7-def-wedge-product-dx-dy'],
'checkpoint-16-6-degree-matches-curve':['c13s3-def-work-integral','c16s5-ex-form-pulled-back-parabola'],
'checkpoint-18-1-hole-clockwise':['c14s6-a-hole-must-be-included-in-the-boundary','c18s1-ex-rectangle-positive-boundary'],
'checkpoint-18-1-which-side-forces-the-walk':['c15s5-subsec-surface-boundary-orientation'],
'checkpoint-18-4-curl-meaning':['c17s2-def-exterior-derivative-plane-1-form','c14s2-thm-green-circulation'],
'checkpoint-18-5-why-curl-appears':['c17s2-thm-exterior-derivative-work-form-is-curl'],
'checkpoint-18-6-form-degree-jump':['c17s3-thm-d-flux-is-divergence-volume-form'],
'checkpoint-19-2-divergence-free-still-moves':['c19s2-incompressible-flow-and-divergence-free-fields','c19s2-expansion-compression-and-the-material-derivative'],
}.items():
 W[k]['support_ids']=ss

R18={
'cc-surface-degree':'degree 1','cc-solid-degree':'degree 2','cc-interval-boundary':'b-a gives f(b)-f(a), compatible with positive traversal','cc-inner-clockwise':'the region stays on the left','cc-upward-boundary':'counterclockwise viewed from the upward normal (right-hand rule)','cc-boundary-of-boundary':'box edges cancel in oppositely oriented pairs','cc-d2-ddf':'curl grad f=0 for C2 f','cc-d2-1form':'div curl F=0 for C2 F','cc-closed-nonzero':'the loop can surround a domain hole; closedness alone is local','cc-defined-inside':'the interior derivative and theorem need coefficients on a neighborhood of the whole filling',
'sk-df':'(2xy+sin x)dx+(x²+z³)dy+3yz² dz','sk-plane-1form':'(y+1)dx wedge dy','sk-space-1form':'omega=d(xyz); d omega=0, so the represented curl vector is (0,0,0)','sk-dPhi':'2(x+y+z)dx wedge dy wedge dz; this is div(x²,y²,z²)','sk-work-1form':'omega=P dx+Q dy+R dz; d omega has coefficients (R_y-Q_z,P_z-R_x,Q_x-P_y)','sk-flux-2form':'Phi=P dy wedge dz+Q dz wedge dx+R dx wedge dy; dPhi=(P_x+Q_y+R_z)dV','sk-line-integral':'integral of P dx+Q dy on the same positively oriented boundary','sk-flux-integral':'integral of P dy wedge dz+Q dz wedge dx+R dx wedge dy on outward boundary',
'pr-interval-ftc':'f(5)-f(-2)=105; integral_-2^5(3x²-4)dx=105','pr-rectangle-green':'curl coefficient=2x-2y; double integral over [0,3]x[0,2] is 6','pr-rectangle-direct':'bottom 9/2, right 18, top -33/2, left 0; sum 6','pr-triangle-area':'d(x dy)=dx wedge dy, so half*4*3=6','pr-annulus':'outer 9pi, inner -pi, total 8pi','pr-ellipse':'d omega=dx wedge dy; ellipse area=pi*3*2=6pi','pr-hemisphere-stokes':'curl area form=2 dx wedge dy; use disk radius 2, giving 8pi','pr-any-surface':'3 dx wedge dy=d(3x dy); boundary unit circle gives 3pi','pr-box-divergence':'dPhi=3dV; box volume 6; answer18','pr-box-faces':'positive x,y,z faces each contribute6, the three zero-coordinate faces contribute0; sum18','pr-ball-flux':'3 times 4pi a³/3=4pi a³','pr-curl-flux':'curl(y,z,x)=(-1,-1,-1), constant divergence0, hence total flux0','pr-angle-form':'r(t)=(cos t,sin t) pulls the form back to dt; result2pi. Undefined origin forbids Green on the whole disk','pr-inverse-square':'normal component=1/a², area=4pi a², flux4pi; form undefined at origin','pr-square-orientation':'counterclockwise1, clockwise-1; only boundary orientation changed','pr-disk-downward':'induced boundary clockwise; integral=-2pi','pr-shell-orientation':'outer radius2 normal away from origin; inner radius1 normal toward origin','pr-shell-flux':'outer4pi plus inner-4pi=0, consistent with zero divergence throughout shell','pr-exact-no-boundary':'Stokes gives integral_S d eta=integral_empty eta=0, subject to the stated calculus regularity','pr-exact-solid':'integral_boundaryE d omega=integral_E d²omega=0; flux of a C2 curl through a closed boundary is0',
'cap4-object':'interval; plane region; oriented surface in space; solid','cap4-boundary':'b-a; counterclockwise outer/clockwise holes; right-hand induced curve; outward closed surface','cap4-form':'f; Pdx+Qdy; Pdx+Qdy+Rdz; Pdy dz+Qdz dx+Rdx dy','cap4-derivative':'f prime dt; (Q_x-P_y)dxdy; curl flux form; divergence volume form','cap4-forms-version':'integral_boundary M omega=integral_M d omega with appropriate degree and compatible orientation','cap4-classical-version':'FTC; Green circulation; classical Stokes; divergence theorem','cap4-warning':'respect endpoint signs, hole boundaries, induced normal/boundary orientation, and defined smooth coefficients on the full region',
'cap3-direct':'unit circle pulls -y dx+x dy back to dt; integral2pi','cap3-disk':'d omega=2dxdy; disk area pi gives2pi','cap3-hemisphere':'same boundary gives2pi; direct pullback with outward normal integrates2sin(phi)cos(phi)dphi dtheta to2pi','cap3-cone':'On r in [epsilon,1], theta in [0,2pi], pullback d omega=2r dr dtheta, integral2pi(1-epsilon²). Outer2pi plus clockwise inner-2pi epsilon² matches. Missing tip contributes2pi epsilon²; limit2pi. Reversing orientations negates every value',
'mistake-closed-form':'closedness need not imply exactness on punctured plane; actual unit-circle integral2pi','mistake-annulus':'inner circle is part of the boundary and is clockwise','mistake-either-orientation':'a fixed normal forces one boundary orientation; switching it changes the sign','mistake-disk-no-volume':'a disk alone is not a closed solid boundary; upward flux of (0,0,1) ispi','mistake-zero-divergence':'the ball includes an undefined origin; actual sphere flux4pi','mistake-cube-edges':'each cube edge belongs to two oppositely oriented faces and cancels in the surface boundary','mistake-curl-free':'angle field is curl-free on punctured plane but has integral2pi','mistake-same-boundary':'same-boundary invariance holds for exact 2-forms, not arbitrary Phi. Phi=z dxdy gives0 on flat unit disk and pi/2 on upward graph z=1-x²-y² with the same boundary'
}
for suf,a in R18.items():
 sup=['c18s2-thm-generalized-stokes','c18s1-def-outward-first-convention']
 if suf.startswith('sk-') or 'd2' in suf:sup+=['c17s1-def-exterior-derivative-0-form','c17s2-def-exterior-derivative-space-1-form','c17s2-def-exterior-derivative-plane-1-form','c17s3-def-exterior-derivative-space-2-form','c17s4-thm-d-domega-zero']
 elif any(t in suf for t in ['angle','inverse','closed-nonzero','zero-divergence','curl-free','defined-inside']):sup+=['c17s2-ex-hidden-singularity-breaks-theorem','c17s3-ex-hidden-singularity-source']
 else:sup+=['c16s6-def-integral-1-form-curve','c16s6-def-integral-2-form-surface','c18s4-thm-green-as-stokes','c18s6-thm-divergence-theorem-as-generalized-stokes']
 w('c18s10-ex-'+suf,a,sup)

W['c18s10-ex-pr-any-surface']['solution_outline']='Under the intended additional compactness assumption, 3 dx wedge dy=d(3x dy) and the induced CCW unit-circle integral gives3pi. As literally stated, the task is under-specified: the smooth upward exterior planar surface z=0,x²+y²>=1 has the same geometric boundary circle (induced clockwise) and integral3dxdy diverges. The compact Stokes theorem cannot apply. Add compact and state induced CCW orientation.'
W['c18s10-ex-pr-any-surface']['verdict']='GF-05: hypothesis gap; intended answer3pi conditional on compactness'

group('c19s6-project-pipe-network','M1 prime=5-.4M1+.2M3; M2 prime=.4M1-.3M2; M3 prime=.3M2-.2M3-2. Summing cancels all three internal flows and leaves3. Replacing pump5 by2 gives total derivative0. Each internal transfer appears with opposite signs at its two tanks, the finite analogue of boundary cancellation.',['c19s1-def-integral-balance-law','c18s1-ex-boundary-orientation-of-a-box'])
group('c19s6-project-heat-plate','u_t=-2 alpha pi²u and Delta u=-2pi²u; each boundary sine vanishes and t=0 gives the required initial data. For alpha>0 the exponential decays. H(t)=4 exp(-2alpha pi²t)/pi². The (3,1) spatial mode has Delta eigenvalue -10pi² and exponential exp(-10alpha pi²t), five times faster decay. Larger curvature imbalance creates greater diffusive flux.',['c19s3-def-heat-equation','c19s3-ex-warm-bump-on-a-rod','c10s3-thm-fubini-rectangles'])
group('c19s6-project-stream-functions','With C2 psi, div(psi_y,-psi_x)=psi_yx-psi_xy=0. For psi=sin x sin y, v=(sin x cos y,-cos x sin y). Its dot product with grad psi is identically0, so the chain rule makes psi constant along each differentiable trajectory. Scalar curl=-psi_xx-psi_yy=-Delta psi=2sin x sin y for the example.',['c9s3-thm-equality-of-mixed-partials','c8s1-thm-chain-rule-curve','c19s2-def-continuity-equation'])
group('c19s6-project-maxwell','dE=(E3_y-E2_z)dy dz+(E1_z-E3_x)dz dx+(E2_x-E1_y)dx dy. dB=(B1_x+B2_y+B3_z)dx dy dz. Thus Faraday is curl E+B_t=0 and dB=0 is div B=0. Applying d gives (dB)_t=0 because d²E=0 and C2 space/time derivatives commute; this is redundant with the magnetic constraint, not an additional independent Maxwell equation.',['c17s2-def-exterior-derivative-space-1-form','c17s3-def-exterior-derivative-space-2-form','c19s4-subsec-charge-conservation-d-squared'])
group('c19s6-project-harmonic','x,y,xy have zero xx and yy sum. Boundary values for x: bottom/top x, left0,right1; for y: bottom0,top1,left/right y; for xy: bottom/left0,top x,right y. For a x+b y+c xy, linearity gives Delta=0. The supplied maximum principle excludes a nonconstant function attaining its global maximum inside. Its source proof has GF-03 missing connectedness support; applying the correctly stated theorem is allowed.',['c19s5-def-harmonic-function','c19s5-thm-no-interior-maximum'],'supported use of supplied statement; GF-03 proof limitation')

group('c20s1-proj-quadric-surfaces','A complete gallery can choose cylinder x²+y²=4 (z-slices circles, x/y-slices parallel vertical lines); parabolic cylinder y=x² (z-slices parabolas, x=c gives y=c² vertical line); bowl z=x²+y² (horizontal circles, coordinate planes parabolas); saddle z=x²-y² (horizontal hyperbolas, coordinate sections opposite parabolas); ellipsoid x²/9+y²/4+z²=1 (three central ellipses with semiaxes3,2,1); one-sheet x²+y²-z²=1 (horizontal circles radius sqrt(1+z²), central vertical hyperbolas). Two-sheet z²-x²-y²=1 has pieces z>=1,z<=-1; cone z²=x²+y² has two nappes joined at the vertex and is connected. Translated ellipsoid has center(1,-2,0), semiaxes(2,3,4). A missing variable means translation-invariant extrusion. Names/traces/hand sketches and the comparison questions require the geometric meaning of connected pieces, not the clopen criterion.',['c20s1-proj-quadric-surfaces','c4s4-ex-hyperboloid-one-sheet','c4s4-ex-hyperboloid-two-sheets'])
group('c20s1-proj-tangent-planes','Use the supplied quadratic roof at its seed point: f=103/16, gradient=(9/8,-1/8), and L is that value plus gradient dot(h,k). Exact error E=h²/8-k²/16+hk/8; for(h,k)=(.2,-.1), E=3/1600. Scaling any fixed direction by t makes E proportional to t², so |E|/norm(h,k) tends0 and |E|/norm² stays bounded. Tabulate t=1,.5,.25. Draw L with the smooth graph. For the cone sqrt(x²+y²), coordinate slices are absolute values and no linear functional matches all directions at0. A few slices cannot establish a uniform differentiability estimate.',['c7s3-def-differentiability-two-variables','c20s1-proj-tangent-planes'])
group('c20s1-proj-gradient-fields','Choose f1=4-x²/4-y² and f2=xy. Gradients are(-x/2,-2y) and(y,x); contour tangent (dx,dy) obeys grad f dot tangent=0. Pick three regular points per map, e.g. for f1(2,0),(0,1),(2,1) with tangents(0,1),(1,0),(-2,1); for f2(1,1),(1,2),(2,3) with tangents(1,-1),(1,-2),(2,-3). Origins are a strict maximum (Hessian diag(-1/2,-2)) and a saddle (Hessian [[0,1],[1,0]]). Gradient paths cross regular contours normally, moving toward the hill maximum; the saddle attracts only along one line and repels along another. Optional log r has gradient(x/r²,y/r²), no critical points, and an excluded singular origin.',['c7s2-def-gradient','c9s1-thm-gradient-normal-level-curve','c9s3-def-hessian-matrix-two-variables','c9s4-thm-second-derivative-test','c20s1-proj-gradient-fields'])
group('c20s1-proj-parameter-grids','Differentiate the supplied coordinates componentwise. Sphere r_theta=(-a sinphi sintheta,a sinphi costheta,0), r_phi=(a cosphi costheta,a cosphi sintheta,-a sinphi), area a² sinphi. Torus r_theta=(-(R+r cosphi)sintheta,(R+r cosphi)costheta,0), r_phi=(-r sinphi costheta,-r sinphi sintheta,r cosphi), area r(R+r cosphi) for R>r>0. Cone r_theta=(-s sintheta,s costheta,0),r_s=(costheta,sintheta,1), area s sqrt2. Periodic theta seams repeat; torus phi is periodic; sphere poles collapse theta; cone apex s=0 is nonregular. Grid crowds near poles/apex and on inner torus. Distinguish a sphere coordinate singularity from a genuine cone tip.',['c15s1-def-smooth-regular-surface-patch','c15s3-thm-flux-parametrized-surface','c20s1-proj-parameter-grids'])
group('c20s2-proj-constrained-design','For open rectangular volume32, area A=xy+2xz+2yz and xyz=32. Eliminate z; stationarity gives x=y=4,z=2,A=48, and reduction in xy plus x+y>=2sqrt(xy) gives the global minimum. Closed cylinder: area2pi r²+2V/r, critical h=2r,r³=V/(2pi), second derivative positive and area blows up at endpoints. Open cylinder: area pi r²+2V/r, h=r,r³=V/pi. Square-section closed tube: area2x²+4V/x, minimum length=x=V^(1/3). Lagrange gives the same relations; positive domains and endpoint behavior verify minima rather than only stationarity.',['c9s5-thm-lagrange-one-constraint','c20s2-proj-constrained-design'])
group('c20s2-proj-least-squares','For line data (0,1),(1,2),(2,2),(3,4),(4,5), residuals mx+b-y give normal equations30m+10b=38,10m+5b=14; m=1,b=4/5. H=2[[30,10],[10,5]] positive definite (det200). For quadratic data (-2,5),(-1,2),(0,1),(1,2),(2,6), normal equations34A+10C=48,10B=2,10A+5C=16 give A=8/7,B=1/5,C=32/35. H=2X^T X positive by independent columns, since a quadratic zero at five distinct x is zero. The supplied plane example gives a=7/5,b=37/15,c=9/5; the direct sum-of-squares proof at237–266 establishes global minimality without importing a general 3D Hessian test. Residual vector is perpendicular to every model-data column by the normal equations. Plot points and each fit from these formulas.',['c9s3-def-hessian-matrix-two-variables','c20s2-proj-least-squares'])
group('c20s2-proj-entropy','For S=-sum p_i log p_i, gradient components=-(log p_i+1); Hessian diagonal=-1/p_i. On any nonzero feasible segment its second derivative is negative, so an interior stationary point is the unique global maximum, with continuity 0log0=0 handling boundary comparison as explained locally. Normalization alone gives p_i=1/n, S=log n. For energies(0,1,2) and0<U<2, two independent constraint gradients(1,1,1),(0,1,2) satisfy Ch9 two-constraint hypotheses. Lagrange gives p=C(1,q,q²),q=exp(-beta)>0,C=1/(1+q+q²). U(q)=(q+2q²)/(1+q+q²) has derivative(q²+4q+1)/(1+q+q²)²>0 and limits0,2, so a unique positive q exists by IVT. U=1/2 gives q=(-1+sqrt13)/6 and those probabilities. EndpointU require a point mass, not finite beta.',['c9s5-thm-lagrange-two-constraints','c20s2-proj-entropy'])
group('c20s2-proj-gradient-descent','Choose f1=.5(x-2)²+2(y+1)² and g1=x²-y². With f1 start(6,4), alpha=.2, x_n=2+4(.8)^n,y_n=-1+5(.2)^n. Five steps are(5.2,0),(4.56,-.8),(4.048,-.96),(3.6384,-.992),(3.31072,-.9984); f_n=8(.64)^n+50(.04)^n strictly decreases to0. Alpha=.1 gives factors(.9,.6); alpha=.6 gives(.4,-1.4), so bouncing y diverges. For g1 start(1,1),alpha=.2 gives(.6^n,1.4^n), with g_n=.36^n-1.96^n falling while escaping. Hessian eigen-directions explain stable bowl directions versus saddle instability. Hand arithmetic and plotted iterates suffice; no convergence theorem is claimed.',['c7s2-def-gradient','c9s4-thm-second-derivative-test','c20s2-proj-gradient-descent'])
group('c20s3-proj-mass-from-density','For the supplied equal-area grid, each cell has area4; weighted density sum gives mass60.8 and average60.8/24=38/15. Draw six cell centers with tabulated densities. Each equal absolute measurement error has the same mass weight4; larger density values do not amplify an equal absolute measurement error. Unequal cells require their individual areas. Midpoint versus corner sampling changes sample locations and bias; smooth data usually improves with refinement but noisy/jumping measurements give no guaranteed monotone improvement. Units are density times area (or volume), and the largest density is simply the largest listed cell value.',['c10s1-def-double-integral','c20s3-proj-mass-from-density'])
group('c20s3-proj-moments-of-inertia','A complete choice is the uniform supplied rectangular plate, mass4 and Iz=20/3. More generally rectangle sides a,b gives Iz=M(a²+b²)/12,Ix=Mb²/12,Iy=Ma²/12, confirming Iz=Ix+Iy. A disk gives Iz=MR²/2; annulus M(Ro²+Ri²)/2; solid ball 2MR²/5; cylinder about its central axis MR²/2. All follow integrating squared perpendicular distance against density in suitable Cartesian/polar/spherical coordinates. Expanding distance to an axis shifted d gives Icm+Md² because center-of-mass first moments vanish. Moving fixed mass farther out increases I; increased outer density increases the weighted contribution (state whether total mass is held fixed). Units mass times length squared.',['c20s3-proj-moments-of-inertia','c10s5-thm-double-integrals-polar','c11s1-thm-fubini-boxes'])
group('c20s3-proj-change-of-variables','Differentiate each supplied map: shear J=1 and area1; diagonal stretch J=ab and area|ab| for nonzero a,b; trapezoid J=1+u with area3/2 and brightness x+y integral2. Fold(u²,v) on[-1,1]x[0,1] has J=2u, reverses sign across u=0 and double covers the image; integral|J|=2 over full domain but restricting u>=0 gives correct image area1 and brightness integral. Polar annulus r in[0,1],angle in[0,2pi] with radius1+r gives J=1+r, area3pi, periodic seam only. Choose brightness1 for a complete option, yielding the same area. Signed J controls oriented integrals; |J| controls ordinary area. A zero-J line collapses rank there, not necessarily a whole two-dimensional region.',['c12s3-thm-change-of-variables-plane','c16s5-def-pullback-coordinate','c20s3-proj-change-of-variables'])
group('c20s3-proj-monte-carlo','For seed disk radius2 in B=[-2,2]², use g=f inside disk and0 outside; estimator16 times the sum over all N divided by N. The exact reference is12pi for the supplied f. Independent uniform coordinate draws implement independent uniform points. Estimate values at N=100,500,1000,5000 and repeat; variation need not shrink monotonically in any one run. Enlarging B wastes samples and generally increases variability; outside zeros retain the box-average identity. Appendix G gives the actual sampler and masks function evaluation to the region. This is an explicitly tabulated numerical experiment, not a law-of-large-numbers proof; project lacks a navigation pointer to its later recipe. The actual Appendix G function was executed for seed pond f=5-x²-y². NumPy seed20260920 gave estimates37.400011,38.372546,35.625150,37.514189 for N=100,500,1000,5000; seed20260921 gave40.461724,38.110622,39.686166,37.595213. Exact12pi=37.69911184. These show run variation and nonmonotone errors; they do not prove convergence.',['c20s3-proj-monte-carlo','appG-numint-monte-carlo-estimate'],'GF-04: computational recipe exists later; local navigation gap')
group('c20s4-project-work-around-closed-curves','Choose unit CCW circle and F=(-y,x): r=(cos t,sin t), work form pulls back to dt and integral2pi; d omega=2dxdy so Green gives2pi; reverse gives-2pi. The field helps CCW travel and cannot be a gradient (curl2). Compare F=(2x,2y)=grad(x²+y²), whose closed work is0. Angle field has curl0 only off the origin yet circle integral2pi; its enclosed disk is inadmissible. These cases settle sign, conservativity, and domain questions.',['c16s6-def-integral-1-form-curve','c18s4-thm-green-as-stokes','c17s2-ex-hidden-singularity-breaks-theorem','c20s4-project-work-around-closed-curves'])
group('c20s4-project-flux-through-complicated-surfaces','For supplied dome z=4-x²-y²,r<=2 and radial field(x,y,z), close with basez=0. Volume=8pi, divergence3 gives total24pi; base flux0 so dome24pi. For upper hemisphere and F=(0,0,z), base0 and divergence1 give curved flux2pi a³/3. For cylindrical side J=(x,y,1), volume flux2pi a²h, caps+pi a² and-pi a² cancel, so side2pi a²h. An omitted box face is handled by total flux minus that face. State outward normals for each piece and negate all when reversing orientation. The flux form coefficients are exactly the chosen field components.',['c15s3-thm-flux-parametrized-surface','c18s6-thm-divergence-theorem-as-generalized-stokes','c20s4-project-flux-through-complicated-surfaces'])
group('c20s4-project-greens-theorem-area-from-gps','Use the provided planar polygon: ordered CCW shoelace sum/2=12 square coordinate units. Reverse ordering gives-12. Integrate (xdy-ydx)/2 along each straight edge to obtain its cross-product term; Green makes the sum equal area for a simple CCW boundary. Wrong vertex order may create crossings; cancellation then gives signed lobes and need not give geometric union area. Clockwise hole boundaries subtract holes. A rough grid count checks size, while curved boundaries introduce polygonal approximation error. The optional real-GPS route requires a chosen local map/projection; the supplied planar dataset is a fully supported path and no geodesy prerequisite is imposed.',['c18s4-thm-green-as-stokes','c20s4-project-greens-theorem-area-from-gps'])
group('c20s4-project-divergence-theorem-flux-balance','Choose J=(x²,y,z) on unit cube. Divergence=2x+2 integrates to3. Positive coordinate faces contribute1 each, opposite faces0, total3 and residual0. Midpoint quadrature is already exact for this linear volume integrand and constant face integrands, so refinement keeps residual0 rather than strictly shrinking it. Reversed normals negate flux; nonzero residual can diagnose orientation/formula/quadrature error. Divergence-free alternatives give total0. For continuity choose rho=10-t,J=(x,0,0),s=0: storage rate-1 balances outgoing1 on the unit cube.',['c18s6-thm-divergence-theorem-as-generalized-stokes','c19s2-thm-local-balance-law','c20s4-project-divergence-theorem-flux-balance'])
group('c20s5-project-1-translate-classical-into-forms','Choose CCW unit-circle rotation F=(-y,x), omega=-y dx+x dy,d omega=2dxdy. Direct integral2pi equals disk integral2pi. Translation table: vector F -> work form omega; directed displacement -> pullback dt; scalar curl2 -> exterior derivative2dxdy; oriented boundary -> counterclockwise circle. For a flux option use unit-cube radial field and Phi=xdy dz+ydz dx+zdx dy,dPhi=3dV; each positive face1,total3. Forms keep orientation signs explicit.',['c16s6-def-integral-1-form-curve','c17s2-def-exterior-derivative-plane-1-form','c18s2-thm-generalized-stokes','c20s5-project-1-translate-classical-into-forms'])
group('c20s5-project-2-closed-not-exact','Angle omega1=(-y dx+x dy)/(x²+y²) is closed on punctured plane, unit-circle2pi and a circle wholly in x>0 has0 by local potential arctan(y/x). Thus not globally exact; twice winding gives4pi. Radial omega2=(x dx+y dy)/(x²+y²)=d log sqrt(x²+y²) is globally exact on punctured plane and both loop integrals are0: this option correctly distinguishes a hole from an automatic obstruction for every form. Translated angle omega3 repeats the first calculation about its shifted puncture. Choose a half-plane for a legitimate smaller-domain angle; a slit plane gives a continuous branch. Winding and angle questions have a conditional answer for omega2, not a claim that it is also nonexact.',['c17s5-def-exact-form','c17s5-def-closed-form','c17s2-ex-hidden-singularity-breaks-theorem','c20s5-project-2-closed-not-exact'])
group('c20s5-project-3-generalized-stokes-cube','Unit cube radial flux: dPhi=3dV, interior3, positive faces1 each, opposite faces0. Rectangular box[a,b,c] and field(x²,y,z): dPhi=(2x+2)dV, integral bc(a²+2a), positive faces a²bc,abc,abc and three zero faces. Unit-square omega=(x²+y)dx+xy dy: d omega=(y-1)dxdy, integral-1/2, direct edges1/3+1/2-4/3+0=-1/2. Rectangle[-y dx+x dy] yields2ab with compatible orientations. Give all six/four boundary pieces, outward/left conventions, and negate both sides for opposite region orientation.',['c17s2-def-exterior-derivative-plane-1-form','c17s3-def-exterior-derivative-space-2-form','c18s1-def-outward-first-convention','c18s2-thm-generalized-stokes','c20s5-project-3-generalized-stokes-cube'])
group('c20s5-project-4-orientation-errors','For annulus inner radius1 outer2 with omega=xdy, correct outer4pi plus inner-pi=3pi; erroneous CCW inner gives5pi. Draw arrows with region on left. For a box face, reversing one normal changes its contribution from f to-f and total by-2f. Swapping surface parameters negates cross product and signed flux; unsigned area stays unchanged. Practical checks: select normal first, induce boundary by right-hand rule, include every hole boundary, and compare sign with physical outward crossing.',['c18s1-def-positive-boundary-orientation-plane','c18s1-def-boundary-orientation-of-a-surface','c16s6-thm-reparametrize-surface','c20s5-project-4-orientation-errors'])
group('c20s6-proj-quaternions','Use the book quaternion multiplication rules i²=j²=k²=ijk=-1,ij=k,ji=-k, and uv=-u dot v+u cross v. Worked examples(1+i)(1-i)=2 and(i+j)(i-j)=-2k show planar norm/rotation multiplication and noncommutativity. Diagram oriented i,j,k and compare scalar dot versus normal-vector cross versus area-measuring wedge. The requested historical discussion is a writing/research assignment; historical claims require the explicitly requested bibliography, not unannounced mathematical prior knowledge.',['c20s6-proj-quaternions','c2s7-def-wedge-linear-measurements'])
group('c20s6-proj-cross-product','Three worked examples: e1 cross e2=e3; e2 cross e1=-e3; (1,0,1)cross(0,1,0)=(-1,0,1), normsqrt2. The three signed projected areas agree with dy dz,dz dx,dx dy evaluations. Diagram the ordered parallelogram. Cross product packages a normal and area efficiently in oriented Euclidean R3 and gives r_u cross r_v for flux; forms make the measuring degree and orientation explicit without confusing vector and area-measurement types.',['c16s3-def-wedge-product-two-covectors','c16s3-ex-tilted-surface-patch','c16s5-def-pullback-coordinate','c20s6-proj-cross-product'])
group('c20s6-proj-ftc','Three complete examples: on[1,4],integral d(x²+1)=15=f(4)-f(1); unit-square integral_boundary xdy=1=integral dxdy; unit-cube radial flux3=integral3dV. Include the supplied four-row translation table (FTC, Green, Stokes, divergence), objects and induced boundaries. Signs make internal pieces cancel and retain only boundary data. This satisfies the three-example requirement; a fourth sphere rotation example is optional.',['c18s2-thm-generalized-stokes','c18s3-thm-ftc-as-stokes','c18s4-thm-green-as-stokes','c18s6-thm-divergence-theorem-as-generalized-stokes','c20s6-proj-ftc'])
group('c20s6-proj-conservation','Choose dye in a fixed unit cube with rho=10-t for0<t<10,J=(x,0,0),s=0. Stored amount10-t has rate-1; right-face outgoing flux1, other faces0. Local rho_t+divJ=-1+1=0. Draw outward right flux, label density/flux/source units. Integrating the local equation and using divergence gives the balance; the reverse every-region argument uses continuity and small neighborhoods. Differentiating a fixed-domain integral invokes the stated19.2 result whose full support has GF-01 extension limitation. Physical sign: outgoing flux subtracts storage; positive s adds production.',['c19s1-def-integral-balance-law','c19s2-thm-local-balance-law','c18s6-thm-divergence-theorem-as-generalized-stokes','c20s6-proj-conservation'])
W['c20s6-proj-quaternions']['support_ids']=['def-c2s2-quaternion','c2s3-def-dot-cross-from-quaternions','c2s7-def-wedge-linear-measurements']

wrappers=[];sections=[]
for prefix in ['ch16','ch17','ch18','ch19','ch20','appF','appG']:
 base=ROOT/('source/appendices' if prefix.startswith('app') else 'source/chapters')
 wrapper=next(base.glob(prefix+'*/*.ptx'));wrappers.append(wrapper)
 for inc in E.parse(str(wrapper)).findall(XI):sections.append(wrapper.parent/inc.get('href'))
rows=[];keys=set();exclusions=[]
def add(k,path,line,kind,group_id,prompt=''):
 if k in keys:return
 keys.add(k);v=W.get(group_id)
 if not v:raise ValueError((k,group_id))
 rows.append({'task_key':k,'path':path,'line':line,'kind':kind,'witness':group_id,'prompt':prompt,'verdict':v['verdict'],'support_ids':v['support_ids']})
assigned=[t for t in T if t['chapter']['id'].startswith(('ch16','ch17','ch18','ch19','ch20','appF','appG'))]
for t in assigned:
 k=t['task_key']
 if t['kind']=='formal':add(k,t['path'],t['lines'][0],'formal',k,t['text'].split('?')[0][:140])
 elif t['kind']=='assessment_bundle_candidate':
  if k in W:add(k,t['path'],t['lines'][0],'project bundle',k,t['text'][:100])
  else:exclusions.append((k,'Expository preview subsection, not an additional student task. Its nested formal checkpoint is separately covered.'))
 else:
  tree=E.parse(str(ROOT/t['path']));nodes=[n for n in tree.iter() if n.sourceline==t['lines'][0]]
  n=next((n for n in nodes if n.tag=='p'),nodes[0] if nodes else None)
  owner=next((a.get(ID) for a in [n]+list(n.iterancestors()) if a.get(ID) in W),None) if n is not None else None
  if owner:add(k,t['path'],t['lines'][0],'directive candidate; project subtask',owner,t['text'][:150])
  elif 'chapter-review-and-capstone' in t['path']:
   target='c18s10-ex-cap4-forms-version' if t['lines'][0]<760 else 'c18s10-ex-cap3-direct'
   add(k,t['path'],t['lines'][0],'umbrella directive',target,t['text'])
  else:exclusions.append((k,'Worked derivation/recipe instruction with its calculation supplied, not a separate assessment. Source calculation checked in semantic pass.'))

# The automated candidate inventory misses verbs and untagged lists. Add every list item
# in every actual Ch19/20 project, even report-deliverable items, plus prompt paragraphs.
for p in sections:
 tree=E.parse(str(p));rel=p.relative_to(ROOT).as_posix()
 for s in tree.findall('subsection'):
  sid=s.get(ID)
  if sid not in W or not sid.startswith(('c19s6-project','c20')):continue
  for n in s.iter('li'):
   if any(a.tag=='li' for a in n.iterancestors()):continue
   txt=' '.join(''.join(n.itertext()).split())
   add(f'{rel}:L{n.sourceline}:li',rel,n.sourceline,'untagged task/question/deliverable',sid,txt)
  for n in s.iter('p'):
   if any(a.tag in ('li','figure','table') for a in n.iterancestors()):continue
   txt=' '.join(''.join(n.itertext()).split())
   if re.search(r'Your task|What to hand in|Write a |Choose |Create |For each |Show that|Check that|Try |Maximize|Find |Derive |at least|two ways|What happens|Reverse',txt):
    add(f'{rel}:L{n.sourceline}:p',rel,n.sourceline,'untagged project prompt/option',sid,txt)

md=['# General forms task witnesses','',f'Snapshot `{SHA}`. Source order and source IDs are authoritative. All assigned sections and their examples, hints, graphics source, tables, and code were semantically read before old dispositions were consulted. No textbook edits.','',
'Each task row includes an exact source identity, a solution witness, its support IDs, and a verdict. The linked witness is part of the row: it supplies actual formulas, sign checks, proof outline, or a complete permitted project choice. Report-deliverable rows inherit the same mathematical witness. Alternative exploratory datasets/software runs are not fabricated as executed; they do not require a universal solution. All high-risk listed options (cone, entropy, fold, closed/exact alternatives) are checked explicitly.','',
f'Inventory contains {len(assigned)} assigned candidates. There are {len(rows)} recorded task identities after adding source list items and prompt paragraphs; overlapping inventory paragraph and containing list-item identities are retained as aliases, not counted as different exercises. {len(exclusions)} inventory candidates are explicitly excluded below.','',
'## Solution witnesses','']
for k,v in W.items():
 md.extend([f'### {k}','',v['solution_outline'],'','Support: '+'; '.join(cite(x) for x in v['support_ids'])+'.','',f"Verdict: {v['verdict']}.",''])
md+=['## Every formal and untagged task identity','','| Task identity and source | Classification/prompt | Solution outline | Support IDs | Verdict |','|---|---|---|---|---|']
for r in rows:
 p=r['prompt'].replace('|',' / ').replace('\n',' ')
 if len(p)>190:p=p[:187]+'…'
 a=f"Use witness `{r['witness']}` above; its computed results and reasoning answer this item."
 if r['kind']=='formal':a=W[r['witness']]['solution_outline']
 a=a.replace('|',' / ')
 md.append(f"| `{r['task_key']}`; `{r['path']}:{r['line']}` | {r['kind']}: {p} | {a} | "+', '.join('`'+x+'`' for x in r['support_ids'])+f" | {r['verdict']} |")
md+=['','## Candidate exclusions','','| Candidate identity | Semantic classification |','|---|---|']
for k,v in exclusions:md.append(f'| `{k}` | {v} |')
md+=['','## Validation and limits','','All assigned XML parsed with lxml. SymPy independently confirmed the quadratic least-squares coefficients `(8/7,1/5,32/35)`, the unequal mixed-partial limits, the positive derivative of the entropy mean-energy function, the rectangle Green integral 6, and the same-boundary counterexample flux pi/2. The source Appendix G midpoint and Monte Carlo function bodies were also executed: constant rectangular quadrature returned24 and an empty Monte Carlo mask returned0; two reproducible pond sampling runs are recorded in the Monte Carlo witness. No rendered-page inspection, graphical production, software installation, general API compatibility test, probabilistic convergence proof, or full textbook correctness certification is claimed. All diagram geometry and labels were read in source.','']
(OUT/'exercise-checks.md').write_text('\n'.join(md),encoding='utf-8')
(OUT/'_data.json').write_text(json.dumps({'witnesses':W,'rows':rows,'exclusions':exclusions,'support_evidence':used},indent=2,ensure_ascii=False),encoding='utf-8')
print('witnesses',len(W),'rows',len(rows),'candidates',len(assigned),'exclusions',len(exclusions))

issues={
'sec-18-chapter-review-and-capstone-problems':['GF-05: any-surface task omits compactness; literal exterior-plane surface has divergent integral'],
'sec-17-the-rule-d-squared-equals-zero':['GF-02: formal coefficient calculation displayed as d(dg) although dg is not C1'],
'sec-17-closed-and-exact-forms':['GF-01: homotopy-grid subsequence/uniform-control premise unavailable; parameter lemma also inherits shared missing support'],
'sec-19-the-continuity-equation':['GF-01: fixed compact solid uniform-continuity estimate extends interval lemma without the shared supporting compactness result'],
'sec-19-maxwell-s-equations-as-a-forms-gateway':['Inherited GF-01 proof dependency through parameter-integral lemma and closed-1-form theorem; local formulas and stated theorem applications checked'],
'sec-19-potential-theory-and-harmonic-functions':['GF-03: relative-open/closed connectedness propagation not supplied; inherited GF-01 parameter lemma proof premise'],
'sec-20-integration-projects':['GF-04: selected Monte Carlo route lacks pointer to later executable sampling recipe; two illustrative runs were executed, not a convergence proof'],
}
coverage=[]
for p in sections:
 r=E.parse(str(p)).getroot();sid=r.get(ID);rel=p.relative_to(ROOT).as_posix();loc=I[sid]
 graphics=[n.get(ID) or f'{rel}:{n.sourceline}' for n in r.iter() if n.tag=='figure']
 rr=[x for x in rows if x['path']==rel]
 coverage.append({'section_id':sid,'snapshot':SHA,'path':rel,'lines':loc['lines'],'section_order':loc['section_order'],'semantic_read':True,'support_verified':sid not in issues,'support_limits':issues.get(sid,[])+['Support verdict concerns the learning/proof dependencies examined, not a global mathematical correctness certification. Supplied theorem roots are permitted.'],'task_witnesses_complete':True,'task_identity_count':len(rr),'graphics_review':{'source':'all embedded source, labels, captions and descriptions read','figure_ids':graphics,'rendered':'not inspected by this worker; no generated assets changed'},'unresolved':issues.get(sid,[])})
wrapper_records=[{'path':p.relative_to(ROOT).as_posix(),'semantic_read':True,'support_verified':True,'limits':'Chapter/appendix introductions and include order read; no hidden prerequisite contract inserted.'} for p in wrappers]
wrapper_records.append({'path':'source/backmatter.ptx','semantic_read':True,'support_verified':True,'limits':'Backmatter wrapper and its referenced content read; no new assessment dependency.'})
(OUT/'coverage.json').write_text(json.dumps({'snapshot':SHA,'assigned_sections':len(coverage),'sections':coverage,'wrappers_and_backmatter':wrapper_records,'source_only_graphics_limit':True,'prior_dispositions_consulted_after_fresh_judgments':True,'task_identity_count':len(rows),'unique_witness_count':len(W),'excluded_inventory_candidates':exclusions},indent=2,ensure_ascii=False),encoding='utf-8')

concepts=[]
def concept(cid,name,typ,scope,mention,explanation,definition,computation,rule,use,extra=None):
 def rec(x):
  if x is None:return None
  if isinstance(x,tuple):return ev(x[0],x[1])
  return ev(x)
 concepts.append({'concept_id':cid,'precise_capability':name,'type':typ,'scope':scope,'first_mention':rec(mention),'first_sufficient_explanation':rec(explanation),'first_definition':rec(definition),'first_worked_computation':rec(computation),'general_rule':rec(rule),'first_required_use':rec(use),'evidence_status':'source verified in assigned range; earliest global occurrences cross-checked with sibling/root where noted','limits':extra or []})
concept('forms.covector.coordinate_basis','Evaluate and represent a covector as a linear scalar measurement','V* x V -> R','Real coordinate Rn; vector/covector distinction','c2s7-subsec-coordinate-measurements','c16s2-def-covector','c16s2-def-covector','c16s2-ex-covector-from-coordinate-readings','c16s2-thm-every-covector-is-combination-of-coordinate-covectors','checkpoint-16-2-vector-vs-covector',['Earlier two-coordinate measuring rules are legitimate special cases.'])
concept('forms.wedge.two_covectors','Evaluate wedge of any two linear scalar measurements','V* x V* -> alternating bilinear scalar forms','Finite-dimensional real coordinate spaces','c2s7-def-wedge-linear-measurements','c2s7-def-wedge-linear-measurements','c2s7-def-wedge-linear-measurements','c16s3-ex-slanted-coordinate-area','c16s3-def-wedge-product-two-covectors','checkpoint-16-3-sign-means-orientation')
concept('forms.wedge.three_coordinate_vs_general','Distinguish coordinate signed volume from arbitrary three-covector expansion','(V*)^3 -> alternating trilinear scalar forms','R3 coordinate volume first; later arbitrary covector algebra','c2s7-def-volume-form-dx-dy-dz','c16s3-ex-triple-wedge-product','c2s7-def-volume-form-dx-dy-dz','c16s3-ex-triple-wedge-product','c16s4-thm-sign-rule-swapping','checkpoint-16-4-sign-as-orientation',['This assigned fragment does not certify earlier Ch11 arbitrary-triple-wedge availability; root audits that distinct use.'])
concept('forms.wedge.graded_sign','Swap homogeneous k- and l-forms and calculate (-1)^(kl)','Lambda^k x Lambda^l -> Lambda^(k+l)','Coordinate sums of wedges; degree ceiling n','c16s4-thm-sign-rule-swapping','c16s4-thm-sign-rule-swapping','c16s4-thm-sign-rule-swapping','c16s4-ex-one-swap-two-swaps','c16s4-thm-sign-rule-swapping','checkpoint-16-4-sign-as-orientation')
concept('forms.pullback.typed','Pull a target form to the parameter domain by differentiating the coordinate map','T* : forms(target)->forms(source)','C1 maps with appropriate parameter domain; not arbitrary identification of dx and du','c12s5-def-pullback-area-form','c16s5-def-pullback-coordinate','c16s5-def-pullback-coordinate','c16s5-ex-pullback-area-form','c16s5-def-pullback-coordinate','checkpoint-16-5-why-pullback-back')
concept('forms.integral.reparametrization','Integrate oriented forms and change compatible once-covering parameters','k-form + oriented k-object -> R','Degrees1,2,3 with stated regularity/coverage; orientation sign retained','c16s6-def-integral-1-form-curve','c16s6-def-integral-1-form-curve','c16s6-def-integral-2-form-surface','c16s6-ex-flux-cylinder-side','c16s6-thm-reparametrize-surface','checkpoint-16-6-why-independence-holds',['Global first line-integral preparation is Ch13; local theorem supports the assigned continuation.'])
concept('forms.d.zero','Differentiate a differentiable scalar function into its linear differential','d : differentiable 0-forms -> pointwise 1-forms','df is the total derivative; mere partial existence is insufficient','c7s3-def-differentiability-two-variables','c17s1-def-exterior-derivative-0-form','c17s1-def-exterior-derivative-0-form','c17s1-ex-drone','c17s1-thm-chain-rule','checkpoint-17-1-measures-not-stores')
concept('forms.d.one','Compute exterior derivative of a C1 work form','d : C1 Omega^1 -> continuous Omega^2','Plane and R3 coordinate definitions','c14s4-thm-greens-for-1-forms','c17s2-def-exterior-derivative-plane-1-form','c17s2-def-exterior-derivative-plane-1-form','c17s2-ex-rotating-air-flow-in-space','c17s2-thm-exterior-derivative-work-form-is-curl','checkpoint-17-2-curl-not-new')
concept('forms.d.two','Compute exterior derivative of a C1 flux form','d : C1 Omega^2(R3)->continuous Omega^3','R3 coordinate basis dy dz,dz dx,dx dy','c15s6-subsec-divergence-in-form-language','c17s3-def-exterior-derivative-space-2-form','c17s3-def-exterior-derivative-space-2-form','c17s3-ex-uniform-source-density','c17s3-thm-d-flux-is-divergence-volume-form','checkpoint-17-3-one-operation-three-names')
concept('forms.d.square_zero','Apply d twice only when the first derivative remains in its declared domain','d² : C2 Omega^k -> Omega^(k+2)','Coordinate C2 functions/forms; classical operator only','c17s4-thm-d-df-zero','c17s4-thm-d-df-zero','c17s4-thm-d-df-zero','c17s4-ex-temperature-gradient-zero-curl','c17s4-thm-d-domega-zero','c17s4-ex-c2-hypothesis',['GF-02: dg outside C1 does not define a counterexample to d²=0.'])
concept('topology.homotopy.uniform_grid','Choose one finite square subdivision whose image cells lie in domain balls','continuous H:[0,1]^2->open D => uniform cell control','Continuous contraction; no derivative/embedded surface assumption','c17s5-thm-simply-connected-potential',None,None,None,None,('c17s5-thm-simply-connected-potential',[458,468]),['GF-01 missing bounded-sequence subsequence/uniform-local-control support. Earlier13.5 finite path subdivision is another unsupported occurrence, not a proof root.'])
concept('forms.closed_one_to_exact','Construct a primitive for a closed C1 1-form on simply connected open R2/R3','closed Omega^1 -> d(phi)','Path connected, simply connected; not higher-degree exactness','c17s5-def-closed-form','c17s5-def-exact-form','c17s5-def-exact-form','c17s5-ex-exact-1-form','c17s5-thm-simply-connected-potential','checkpoint-17-5-local-versus-global',['The statement is correct; its claimed in-book proof has GF-01 unavailable premises.'])
concept('stokes.general_supplied','Use boundary-integral equals exterior-derivative integral under explicit hypotheses','Omega^(k-1) x oriented compact k-object -> equality','Book theorem expressly curves/surfaces/solids dimensions1–3','c18s2-thm-generalized-stokes','c18s2-thm-generalized-stokes','c18s2-thm-generalized-stokes','c18s3-thm-ftc-as-stokes','c18s2-thm-generalized-stokes','checkpoint-18-2-why-omega-one-degree-less',['Supplied general theorem; exact rectangles/boxes and C2 pullback naturality are limited independent proof components, not a full patching proof.'])
concept('analysis.parameter_integral.compact_volume','Pass a time derivative through integration over a fixed compact solid','d/dt integral_E rho = integral_E rho_t','Continuous rho_t on neighborhood; E fixed finite-volume region','c13s6-lem-parameter-integral',None,'c19s2-thm-local-balance-law','c19s2-a-density-profile-moving-down-a-pipe',('c19s2-deriving-the-local-balance-law',[128,149]),'c19s2-thm-local-balance-law',['GF-01: actual uniform estimate is stated, but interval-to-compact-solid support depends on missing compactness/uniform continuity toolkit.'])
concept('pde.balance.localize','Deduce local conservation from all-small-region integral balance','continuous scalar integrand with all local integrals zero -> identically zero','Fixed spatial domain and source terms','c19s1-def-integral-balance-law',('c19s2-deriving-the-local-balance-law',[150,194]),'c19s2-thm-local-balance-law','c19s2-a-density-profile-moving-down-a-pipe','c19s2-thm-local-balance-law','checkpoint-19-2-every-region',['Localization itself is supported by continuity and positivity; derivative interchange is a separate edge.'])
concept('forms.maxwell.local_two_potential','Construct a local vector potential for a closed spatial 2-form','closed Omega^2 on box -> d Omega^1 locally','Explicit box integrals; C2 fields and parameter lemma',('c19s4-subsec-homogeneous-equations-and-potentials',[568,602]),('c19s4-subsec-homogeneous-equations-and-potentials',[588,602]),None,('c19s4-subsec-homogeneous-equations-and-potentials',[588,602]),('c19s4-subsec-homogeneous-equations-and-potentials',[588,602]),('c19s4-subsec-homogeneous-equations-and-potentials',[588,602]),['No general Poincare lemma assumed. Inherits parameter lemma proof limitation.'])
concept('forms.spacetime.d4','Compute coordinate exterior derivative including time and its graded signs','d4=dt wedge partial_t+d_space','Coordinate spacetime with C2 coefficients',('c19s4-subsec-what-changes-in-space-time',[634,652]),('c19s4-subsec-what-changes-in-space-time',[653,665]),('c19s4-subsec-what-changes-in-space-time',[653,665]),('c19s4-subsec-what-changes-in-space-time',[666,719]),('c19s4-subsec-what-changes-in-space-time',[653,665]),'checkpoint-19-4-gateway-elegance',['No Hodge star, Lorentz metric, or coordinate-frame transformation calculation is required by this task.'])
concept('harmonic.mean_value','Prove the circular mean equals center value for planar C2 harmonic functions','harmonic scalar on disk -> circle average equality','Disk closure lies in domain; planar divergence and parameter lemma','c19s5-subsec-mean-value-ideas','c19s5-thm-mean-value-property','c19s5-def-harmonic-function','c19s5-ex-why-harmonicity-needed','c19s5-thm-mean-value-property','checkpoint-19-5-maximum-principle',['Inherits GF-01 parameter lemma proof limitation; the circle computation itself is checked.'])
concept('topology.relative_clopen.connected','Propagate a nonempty relatively open and closed maximum set through a connected domain','nonempty A clopen in connected R -> A=R','Relative topology, not the geometric two-piece picture','c19s5-thm-no-interior-maximum',None,None,None,None,('c19s5-thm-no-interior-maximum',[393,399]),['GF-03 missing criterion; no abstract topology course needed.'])
concept('harmonic.dirichlet_minimum','Compare energy of harmonic u to C1 competitors with same boundary data','E(w)-E(u)=1/2 integral |grad(w-u)|² >=0','C2 u, C1 w on neighborhood, regular bounded region','c19s5-def-dirichlet-energy','c19s5-thm-harmonic-minimize-dirichlet','c19s5-def-dirichlet-energy','c19s5-ex-straight-ramp-minimizes-energy','c19s5-thm-harmonic-minimize-dirichlet','checkpoint-19-5-energy-boundary',['Green identity is derived locally by product rule and divergence; no hidden theorem name needed.'])
concept('probability.monte_carlo.sampling','Generate independent uniform box sample points for the supplied integration estimator','sampler -> N coordinate points; box mean -> estimate','Optional chosen capstone route; software recipe later','c20s3-proj-monte-carlo','appG-numint-monte-carlo-estimate',None,'appG-numint-monte-carlo-estimate','appG-numint-monte-carlo-estimate',('c20s3-proj-monte-carlo',[1120,1128]),['GF-04 P3 navigation only: estimator is locally supplied; no probabilistic convergence proof requested.'])
(OUT/'concepts.json').write_text(json.dumps({'snapshot':SHA,'scope':'Assigned continuation ledger; primary first occurrences outside scope are linked where verified, not inferred from chapter titles.','firstness_limit':'This worker verifies capability stages and exact local/earlier anchors. Global earliest-occurrence claims require the parent merge with foundations/reference/core ledgers; later worked examples here do not imply absence of earlier examples. Null sufficient-support fields record confirmed proof gaps.','concepts':concepts},indent=2,ensure_ascii=False),encoding='utf-8')

edges=[]
def edge(kind,source,target,cap,scope,status='supported'):
 edges.append({'graph':kind,'source_id':source,'target_id':target,'source':ev(source) if source in I else None,'target':ev(target) if target in I else None,'capability':cap,'scope':scope,'status':status})
for r in rows:
 if r['kind'] in ['formal','project bundle']:
  for s in r['support_ids']:edge('learning',s,r['task_key'],'Capability used in solution witness '+r['witness'],'See exercise-checks witness; theorem statement use is distinct from proof validity','hypothesis_gap' if r['verdict'].startswith('GF-05') else 'navigation_gap' if r['witness']=='c20s3-proj-monte-carlo' and s.startswith('appG') else 'supported')
for a,b,c,d in [
('c9s3-thm-equality-of-mixed-partials','c17s4-thm-d-df-zero','cancel mixed derivatives','C2 functions'),
('c9s3-thm-equality-of-mixed-partials','c17s4-thm-d-domega-zero','cancel mixed derivatives','C2 coefficients'),
('c13s6-lem-parameter-integral','c17s5-thm-simply-connected-potential','differentiate radial potential integral','local ball, C1 form'),
('thm-c13s5-path-independence-potential','c17s5-thm-simply-connected-potential','piecewise smooth paths and global potential construction','open path-connected domain'),
('analysis.closed_box_uniform_control','c17s5-thm-simply-connected-potential','uniform grid through bounded-sequence subsequence theorem','continuous square contraction'),
('c13s6-lem-parameter-integral','c19s2-thm-local-balance-law','parameter differentiation idea','interval statement to fixed compact solid extension'),
('analysis.closed_box_uniform_control','c19s2-thm-local-balance-law','uniform continuity on compact spatial set','fixed finite-volume E and continuous rho_t'),
('c18s6-thm-divergence-theorem-as-generalized-stokes','c19s2-thm-local-balance-law','replace outward flux by volume divergence','regular fixed E'),
('c13s6-lem-parameter-integral','c19s5-thm-mean-value-property','differentiate circular average','compact angular interval'),
('c14s3-thm-green-flux-form','c19s5-thm-mean-value-property','zero normal derivative flux','planar harmonic C2 u on disk'),
('c19s5-thm-mean-value-property','c19s5-thm-no-interior-maximum','maximum set locally constant','planar disks'),
('topology.relative_clopen_criterion','c19s5-thm-no-interior-maximum','propagate maximum set to whole connected domain','relative open/closed'),
('c14s3-thm-green-flux-form','c19s5-thm-harmonic-minimize-dirichlet','product-rule integration by parts','C2 harmonic u, C1 competitor fixed boundary'),
('c13s6-lem-parameter-integral','c19s4-subsec-homogeneous-equations-and-potentials','differentiate explicit box primitive','C2 fields'),
('c17s5-thm-simply-connected-potential','c19s4-subsec-homogeneous-equations-and-potentials','local scalar electric potential after vector potential','closed 1-form on a box'),
('c10s3-thm-fubini-rectangles','sec-18-proof-ideas','exact rectangle FTC proof','C1 work coefficients'),
('c11s1-thm-fubini-boxes','sec-18-proof-ideas','exact box FTC proof','C1 flux coefficients'),
('c18s5-pullback-derivative-justification','sec-18-proof-ideas','d(r*omega)=r*domega','C2 parametrization, C1 1-form'),
]:edge('proof',a,b,c,d,'missing_support' if a not in I else 'inherited_missing_premise' if a in ['c13s6-lem-parameter-integral','thm-c13s5-path-independence-potential','c17s5-thm-simply-connected-potential'] else 'supported')
roots=[{'id':'entry.single_variable_calculus','status':'entry assumption','scope':'MVT, FTC, chain/product rules, IVT and basic substitution; not compactness/subsequence theorem'},
{'id':'c18s2-thm-generalized-stokes','evidence':ev('c18s2-thm-generalized-stokes'),'status':'explicitly supplied theorem','scope':'compact piecewise smooth oriented objects of dimension1,2,3 with compatible boundaries and C1 form on neighborhood','proof_ceiling':'18.7 exact rectangle/box proofs, surface naturality, general patching outline'},
{'id':'c12s3-thm-change-of-variables-plane','evidence':ev('c12s3-thm-change-of-variables-plane'),'status':'supplied theorem used for parameter invariance','scope':'stated one-to-one interior, nonzero Jacobian, full target coverage'},
{'id':'c12s4-thm-change-of-variables-space','evidence':ev('c12s4-thm-change-of-variables-space'),'status':'supplied theorem used for volume parameter invariance','scope':'stated regularity/coverage/orientation'},
{'id':'analysis.closed_box_uniform_control','status':'missing support','occurrences':['thm-c13s5-path-independence-potential','c13s6-lem-parameter-integral','c17s5-thm-simply-connected-potential','c19s2-thm-local-balance-law'],'repair':'Shared elementary finite-cover/uniform-control toolkit; do not count these as independent insertions.'},
{'id':'topology.relative_clopen_criterion','status':'missing support','scope':'Elementary connected-domain propagation needed by19.5'}]
(OUT/'graphs.json').write_text(json.dumps({'snapshot':SHA,'edges':edges,'roots':roots,'cycle_check':'No proof cycle found in assigned general-Stokes route: supplied root plus independently checked rectangle/box/naturality components. Missing support is not automatically a cycle.','limits':'Cross-scope theorem statements and shared missing compactness supports are coordinated with root and foundation/reference workers.'},indent=2,ensure_ascii=False),encoding='utf-8')
