from pathlib import Path
from collections import Counter
import json,re
P=Path(__file__).resolve().parents[1];ROOT=P.parents[1]
def read(name):return json.loads((P/name).read_text(encoding='utf-8'))
I=read('id-index.json');S=read('evidence/integration-summary.json');C=read('coverage.json');SHA=S['snapshot']
def loc(key,a=None,b=None):
 r=I[key];return {'snapshot':SHA,'path':r['path'],'xml_id':key,'lines':[a,b] if a else r['lines'],'sha256':r['sha256']}
items=[
('LO-01','ROOT-03 / GF-01','P1','A/F/H','Unprovided compactness consequences in claimed proofs','root','ROOT-03',[loc('thm-c13s5-path-independence-potential',367,373),loc('c13s6-lem-parameter-integral',188,214),loc('c17s5-thm-simply-connected-potential',458,468),loc('c19s2-deriving-the-local-balance-law',128,149)]),
('LO-02','ROOT-01','P2','A/G','Three-covector wedge before its rule','root','ROOT-01',[loc('c11s3-subsec-volume-element',126,148),loc('c11s4-subsec-volume-element',114,127)]),
('LO-03','ROOT-02','P2','F/H','Cylindrical and spherical integration justification bridge','root','ROOT-02',[loc('c11s3-subsec-volume-element',46,53),loc('c11s4-subsec-volume-element',70,85)]),
('LO-04','GF-02','P2','G/H','Exterior derivative displayed outside its stated domain','general-forms','GF-02',[loc('c17s4-ex-c2-hypothesis',126,174)]),
('LO-05','GF-03','P2','A/F','Untaught relative connectedness criterion','general-forms','GF-03',[loc('c19s5-thm-no-interior-maximum',376,401)]),
('LO-06','REF-01','P2','H/I','Nonzero defining gradient missing from two assessments','reference','REF-01',[loc('checkpoint-9-1-gradient-normal-tangent-plane',239,273),loc('checkpoint-9-5-gradients-parallel',135,184)]),
('LO-07','REF-02','P2','G/H','Endpoint hint confuses one-sided feasibility with no tangent','reference','REF-02',[loc('checkpoint-9-6-multiplier-misses-boundary',179,184)]),
('LO-08','FND-01','P2','H/I','Continuity review omits accumulation-point condition','foundations','FND-01',[loc('c6s6-ex-cc-three-conditions',126,133)]),
('LO-09','GS-01','P2','H','Green restatement drops closure of the region','greens-surfaces','GS-01',[loc('c14s4-thm-greens-for-1-forms',201,217)]),
('LO-10','U07','P3','C','Optional Hessian notation preview','foundations',None,[loc('c3s6-subsec-hessian-preview',493,555)]),
('LO-11','FND-02','P3','H/I','Basis-image checkpoint should retain linearity','foundations','FND-02',[loc('checkpoint-3-2-basis-determines-all',241,258)]),
('LO-12','FND-03','P3','H/I','Triangle-equality checkpoint omits zero-vector exception','foundations','FND-03',[loc('checkpoint-1-5-triangle-equality',346,363)]),
('LO-13','GF-04','P3','I','Monte Carlo project lacks a direct sampler reference','general-forms','GF-04',[loc('c20s3-proj-monte-carlo',1035,1128)]),
('LO-14','GF-05','P2','H/I','Any-surface Stokes exercise omits compactness','general-forms','GF-05',[loc('c18s10-ex-pr-any-surface',519,528)])]
out=[]
for key,alias,priority,category,title,f,source,occ in items:
 out.append({'id':key,'worker_aliases':alias,'priority':priority,'category':category,'title':title,'occurrences':occ,'evidence_status':'confirmed local observation' if key!='LO-10' else 'protected optional preview; optional clarity improvement','confidence':'high on literal observation; contextual severity qualified in prose' if key in ['LO-03','LO-09','LO-11','LO-14'] else 'high','details_fragment':f'fragments/{f}/findings.md','detail_id':source})
(P/'findings-index.json').write_text(json.dumps({'snapshot':SHA,'root_cause_count':len(items),'primary_occurrence_count':sum(len(x[-1]) for x in items),'priority_counts':dict(Counter(x[2] for x in items)),'counting_note':'LO-10 is an optional preview improvement, not a required-use defect. Each local passage counts once; downstream uses and echoes are listed separately.','findings':out},indent=2),encoding='utf-8')
lines=['# Independent logical-order audit: findings','',f'Inspected `{SHA}` on `main`. Audit and proposed repairs only; textbook sources are unchanged.','',
'The review establishes **10 required-material/background or scope corrections** (one P1, nine P2) and **four P3 clarity/navigation improvements**, at **20 primary passage occurrences**. The central P1 root is missing compactness support shared by four claimed arguments. These counts group repeated uses of the same missing capability; downstream consumers are not counted again. P3 includes the protected optional Hessian preview.','',
'All194 active sections received a primary semantic reading. Every one of910 formal task elements has a witness; untagged projects and report instructions are also accounted for. This is an audit of learning availability and proof presentation, not a formal certification of all mathematics. See the separate [coverage](scope-and-coverage.md), [task witnesses](exercise-checks.md), and [validation](validation.md).','',
'| ID | Priority | Root cause | Primary occurrences |','|---|---|---|---|']
for x in out:lines.append(f"| {x['id']} | {x['priority']} | {x['title']} | {len(x['occurrences'])} |")
lines += ['', 'Severity is separate from confidence. The shared compactness root is P1 because required arguments explicitly presented as proofs lack a supplied premise; the late-chapter worker rated its individual local occurrences P2 because each is modest to repair. Integration retains the higher priority for the shared dependency. The exact formulas/theorems are not thereby false. The inherited-context judgments in LO-03, LO-09, LO-11 and LO-14 have more editorial uncertainty than their literal source observations.','',
'Independent challenges tried to refute both defects and important protected judgments. See [reference against root](fragments/reference/independent-challenge-root.md), [general forms against foundations](fragments/general-forms/challenges-general-v-foundations.md), [foundations against general forms](fragments/foundations/challenges-foundations-v-general.md), [root against reference](fragments/root/challenges-root-v-reference.md), [root against Green/surfaces](fragments/root/challenges-root-v-greens-surfaces.md), and the [additional Stokes exercise challenge](fragments/root/challenge-stokes-exercise.md).','']
for x in out:
 lines += [f"## {x['id']} — {x['title']}",'',f"Worker records: {x['worker_aliases']}. Priority {x['priority']}; categories {x['category']}.",'']
 for o in x['occurrences']:lines.append(f"- `{o['xml_id']}` — `{o['path']}:{o['lines'][0]}–{o['lines'][1]}`.")
 lines.append('')
 if x['detail_id']:
  text=(P/x['details_fragment']).read_text(encoding='utf-8');pattern=r'^## '+re.escape(x['detail_id'])+r'[^\n]*\n(.*?)(?=^## |\Z)';m=re.search(pattern,text,re.M|re.S)
  assert m,(x['id'],pattern);lines.append(m.group(1).strip().replace('No P1 finding arose in this assigned fresh pass.', 'The late-chapter worker assigned P2 locally; consolidated LO-01 records the shared P1 classification.').replace('contextual severity remains subject to independent challenge','contextual severity was retained after independent challenge'))
 else:
  lines.append('The Section3.6 passage explicitly ends “This is only a preview.” It displays second-partial subscripts before they are taught, but no required task here uses them. Chapter9 supplies the needed definitions before its Hessian work. Classification C/P3, seed U07: protected as a preview, with optional notation clarification. A minimal added sentence is: “The entries of H will be defined in Chapter9; for now, regard H simply as the symmetric matrix describing the quadratic bending.” Retain the earlier quadratic-form lesson and its examples. Verify that required reviews do not import the preview notation; the task witnesses found no such leak. This is an optional refinement, not a recurrence of a blocking dependency.')
 if x['id']=='LO-01':
  t=(P/'fragments/general-forms/findings.md').read_text(encoding='utf-8');m=re.search(r'^## GF-01[^\n]*\n(.*?)(?=^## |\Z)',t,re.M|re.S);lines+=['','### Later occurrences and their exact scope','',m.group(1).strip(),'','Source excerpt for the earliest occurrence: “Compactness of the parameter interval gives a finite subdivision”. Prior A12/L06 endpoint claims are residual at this supporting-premise boundary; prior parameter-lemma and L16 fixed-volume repairs did not supply the missing compactness capability. See LO-01 task routes in13.6,14.5,17.5,19.2/19.4/19.5; these can use correctly supplied statements, but must not be described as completed proofs until repaired. Acceptance: every uniform/subsequence/subdivision step has the stated earlier lemma, correct dimension and neighborhood, and an independent noncircular proof or honest supplied status.']
 if x['id']=='LO-02':lines+=['','Faithful source excerpt: “So” followed by `dx wedge dy wedge dz = r dr wedge dtheta wedge dz`. Existing source/target typing is correct; this finding concerns the missing product/grouping rule. Prior M12 corrected parameter-domain notation but left this broader operation implicit. Acceptance: the early triple manipulation is removed/relocated or preceded by its actual determinant/grouping rule, and all associated task/figure/review references still resolve.']
 if x['id']=='LO-03':lines+=['','Faithful source excerpt: “So the small piece has volume approximately” followed by “Thus the cylindrical volume element is”. Independent challenge confirmed that11.3 already displays the integral formula and warns about multiplicity at328–334. The finding is limited to justification status and complete hypotheses. It is a residual strengthening of the earlier coordinate-factor treatment. Acceptance: one explicit slicing derivation or precise supplied-special-case statement bridges local volume intuition to exact integration; ordinary task witnesses remain valid and oriented/unsigned factors remain separate.']
 lines.append('')
lines += ['## Protected repairs and remaining uncertainty','',
'The author-directed5.2 lesson is preserved. Its ordinary frozen-parameter velocities, regular parameter points, cone/plane contrast and later full tangent-plane proof form a valid sequence. The2.7 two-covector wedge,3.4 independent determinant proof,7.2 gradient derivation, supplied inverse theorem, Gaussian bounded-limit argument, correct multiplicity warnings, surface naturality, and optional Maxwell Hodge preview survived independent challenge.','',
'No known task is left without an outline or explicit defect disposition. Most figures were read in source only. Rendered5.2 was spot-checked; whole-book image layout and print output were not checked. Subjectively, confidence is high in the listed local evidence and broad source coverage, and moderate that this pass found every subtle prerequisite issue; that estimate is editorial judgment, not numerical or mathematical certification. The old preface placeholder and optional “nonempty” cleanup in9.5 are recorded in the reference fragment but are not inflated into additional logical root causes.']
(P/'findings.md').write_text('\n'.join(lines),encoding='utf-8')

scope=['# Scope and coverage','',f'Snapshot `{SHA}`; branch `main`. Initial tracked working tree was clean; the controlling audit brief was the only untracked file. At completion, only that brief and this new audit directory are untracked. No source, old audit report, historical LaTeX/archive, remote, branch or commit was modified.','',
'Actual entry: `source/main.ptx`, expanded in recursive XInclude order, retaining source hashes, original lines, IDs, ancestry and occurrence. The inventory recomputed225 active files:194 sections (145 chapter,49 appendix) plus31 wrappers/frontmatter/backmatter/docinfo files. There are3505 IDs,285 cross-reference records and no parse/include/ID/xref errors. The two inactive source templates are listed in coverage.json; the historical `multivariable_calculus/` tree is excluded.','',
'Entry contract: algebra, trigonometry and single-variable calculus, including limits, continuity, derivative rules, MVT, definite integration, FTC and substitution. No real-analysis/topology/ODE/linear-algebra/exterior-algebra course is assumed. Appendices supply explicit reference routes, not silent earlier lessons. Macro declarations and nonrendered comments do not teach capabilities.','',
f'Primary semantic reading: **{S["semantic_sections"]}/{S["sections"]} sections**, plus all31 nonsection files. Prerequisite-support review records **{S["support_verified_sections"]} sections without an identified unresolved support limitation**; the remainder retain their specific findings/limitations below. This distinction is intentional:194 read does not mean194 logically verified.','',
f'Task coverage: all{S["formal_task_elements"]} formal task elements have witnesses. All{S["all_inventory_candidates"]} mechanical candidates are either witnessed or explicitly classified; none is silently dropped. The{S["task_witness_rows"]} witness/disposition rows also include untagged deliverables and overlapping aliases, so they are not a count of distinct exercises. [Detailed task ledger](task-witnesses.json).','',
'Every figure source/caption/description and visible label code was included in the primary read. Only the5.2 cone figure and adjacent definition/link received a fresh rendered spot-check. Other figures remain source-only; no graphics were regenerated in this audit. Independent challenge covered selected findings and significant protected judgments in every partition; it is not represented as a second full reading of every section. The per-section `independent_challenge_completed` flag remains false where that stronger claim was not earned; `partition_challenge_completed` records the actual narrower check.','',
'The coverage ledger separates inventory, scan, semantic read, support verification, task witness, challenge, rendering and unresolved states. The dependency graphs carry their human-review scope. A successful fixture or build is not a semantic pass.','',
'| Order | Section | Semantic read | Support without open limitation | Tasks | Graphics | Unresolved/support notes |','|---|---|---|---|---|---|---|']
for s in C['sections']:
 unresolved=s.get('unresolved') or s.get('support_limitations') or []
 note='; '.join(str(x) for x in unresolved) if isinstance(unresolved,list) else str(unresolved)
 scope.append(f"| {s['order']} | `{s['section_id']}` | yes | {'yes' if s.get('support_verified') else 'no; see note'} | {'witnessed' if s.get('task_witnesses_complete') else 'incomplete'} | {'source + limited render' if s['graphics_review']['rendered'] else 'source only'} | {note.replace('|','/')} |")
scope += ['', '## Nonsection files','', '| File | Semantic read |','|---|---|']
for w in C['wrappers']:scope.append(f"| `{w['path']}` | yes |")
scope += ['', '## Remaining work boundary','', 'No missing active files or unreviewed source sections remain. The identified logical corrections are proposed, not implemented. Known support limitations remain open in the textbook. Complete per-figure rendered layout, print compilation, arbitrary user-selected empirical project datasets and a formal theorem certification are outside the completed evidence. Strict schema validation fails on the existing backlog; see validation.md.']
(P/'scope-and-coverage.md').write_text('\n'.join(scope),encoding='utf-8')

ex=['# Required-task dependency witnesses','',f'Snapshot `{SHA}`. All910 formal task elements and all1122 scanner candidates are reconciled. Untagged project deliverables and explicit reference/checklist instructions were added by semantic reading. Witnesses give actual computations or solution outlines plus exact earlier/local/scaffold sources. Hints can be announced scaffolds; hidden solutions are not credited as earlier preparation.','',
'This index links the complete human-readable partitions; the [combined JSON](task-witnesses.json) contains source locations, support evidence, verdicts, aliases and exclusions. Repeated paragraph/list identities are deliberately not counted as distinct exercises. A correctly supplied theorem remains usable even where its claimed proof has a finding.','',
'| Partition | Full witnesses |','|---|---|']
for f,label in [('foundations','Chapters1–8'),('reference','Chapter9 and AppendicesA–E'),('root','Chapters10–13'),('greens-surfaces','Chapters14–15'),('general-forms','Chapters16–20 and AppendicesF/G')]:ex.append(f'| {label} | [Witnesses](fragments/{f}/exercise-checks.md) |')
ex += ['', '## High-risk reconstructions','',
'The fragments explicitly solve or reconstruct: regular/degenerate surface maps; directional versus total differentiability; augmented-map implicit systems; singular constraint encodings; all Gaussian finite-limit steps; cylindrical/spherical signs; nonlinear constant-Jacobian and double-cover examples; polygon boundary/area tasks; surface scalar/flux choices; cone-tip truncation; harmonic-energy/maximum explanations; local/global potential and mixed-partial failures; entropy constraints; folded-map projects; and domain-masked Monte Carlo recipes. Exact diagnostic calculations also appear in [counterexample-probes.md](evidence/counterexample-probes.md).','',
'No unsolved required mathematical task is concealed by a generic “standard methods” verdict. Tasks with defective wording have an intended solution and a counterexample to the literal claim recorded. Empirical or open-choice projects have a complete supported route; unperformed external data collection is not fabricated as a completed experiment. AppendixG snippet execution is limited to the focused receipt recorded by its reviewer.']
(P/'exercise-checks.md').write_text('\n'.join(ex),encoding='utf-8')
print('REPORTS',len(items),'roots',sum(len(x[-1]) for x in items),'primary occurrences')
